flowchart LR
  V["Vendedor"]:::actor
  C["Caja"]:::actor
  subgraph SIS["WardrobeFlow — N01 Clientes y suscripciones"]
    c1(["CU01-VEN Gestionar Cliente"])
    c2(["CU02-VEN Renovar Suscripción"])
    c4(["CU03-VEN Gestionar Planes"])
    c3(["CU01-CAJ Cobrar Suscripción"])
  end
  V --- c1
  V --- c2
  V --- c4
  C --- c3
  classDef actor fill:#fff7e6,stroke:#b8860b
