erDiagram
  Prenda ||--o{ CargoPrenda : "IdPrenda"
  Cliente ||--o{ CargoPrenda : "IdCliente"
  Cliente |o--o{ Cliente : "IdClienteReferente"
  PlanSuscripcion |o--o{ Cliente : "IdPlan"
  PlanSuscripcion ||--o{ Contratacion : "IdPlan"
  Empleado ||--o{ Contratacion : "IdVendedor"
  Empleado |o--o{ Contratacion : "IdCaja"
  Promocion |o--o{ Contratacion : "IdPromocion"
  Cliente ||--o{ Contratacion : "IdCliente"
  Cliente |o--o{ Contratacion : "IdReferenteAcreditado"
  Cliente ||--o{ HistorialCobro : "IdCliente"
  Cliente ||--o{ HistorialRenovacion : "IdCliente"
  PlanSuscripcion |o--o{ HistorialRenovacion : "IdPlanAnterior"
  PlanSuscripcion |o--o{ HistorialRenovacion : "IdPlanNuevo"
  Prenda ||--o{ ListaEspera : "IdPrenda"
  Cliente ||--o{ ListaEspera : "IdCliente"
  Prenda ||--o{ MantenimientoPrenda : "IdPrenda"
  Cliente ||--o{ Pedido : "IdCliente"
  Empleado ||--o{ Pedido : "IdEmpleado"
  Empleado |o--o{ Pedido : "IdEmpleadoControl"
  Pedido ||--o{ PedidoHistorial : "IdPedido"
  Pedido ||--o{ PedidoPrenda : "IdPedido"
  Prenda ||--o{ PedidoPrenda : "IdPrenda"
  Cliente |o--o{ Prenda : "IdUltimoCliente"
  Cliente |o--o{ Prenda : "IdClienteActual"
  PlanSuscripcion |o--o{ Promocion : "IdPlan"
  SugerenciaPromocion |o--o{ Promocion : "IdSugerenciaOrigen"
  PlanSuscripcion |o--o{ SugerenciaPromocion : "IdPlan"
  PlanSuscripcion
  Cliente
  Empleado
  Contratacion
  Promocion
  SugerenciaPromocion
  HistorialRenovacion
  HistorialCobro
  Pedido
  PedidoPrenda
  PedidoHistorial
  Prenda
  MantenimientoPrenda
  CargoPrenda
  ListaEspera
