erDiagram
  Cliente |o--o{ Cliente : "IdClienteReferente"
  Cliente ||--o{ ListaEspera : "IdCliente"
  Prenda ||--o{ ListaEspera : "IdPrenda"
  Prenda ||--o{ MantenimientoPrenda : "IdPrenda"
  Cliente ||--o{ Pedido : "IdCliente"
  Empleado |o--o{ Pedido : "IdEmpleadoControl"
  Empleado ||--o{ Pedido : "IdEmpleado"
  PedidoPrenda ||--o{ PedidoFaltante : "IdPedido"
  PedidoPrenda ||--o{ PedidoFaltante : "IdPrenda"
  PedidoFaltante ||--o{ PedidoFaltanteAlternativa : "IdPedido"
  PedidoFaltante ||--o{ PedidoFaltanteAlternativa : "IdPrenda"
  Prenda ||--o{ PedidoFaltanteAlternativa : "IdPrendaAlternativa"
  Pedido ||--o{ PedidoHistorial : "IdPedido"
  Pedido ||--o{ PedidoPrenda : "IdPedido"
  Prenda ||--o{ PedidoPrenda : "IdPrenda"
  Cliente |o--o{ Prenda : "IdClienteActual"
  Cliente |o--o{ Prenda : "IdUltimoCliente"
  Cliente
  Empleado
  Pedido
  PedidoPrenda
  PedidoFaltante
  PedidoFaltanteAlternativa
  PedidoHistorial
  Prenda
  ListaEspera
  MantenimientoPrenda
