erDiagram
  Cliente |o--o{ Cliente : "IdClienteReferente"
  PlanSuscripcion |o--o{ Cliente : "IdPlanSiguiente"
  PlanSuscripcion |o--o{ Cliente : "IdPlan"
  PlanSuscripcion ||--o{ Contratacion : "IdPlan"
  Promocion |o--o{ Contratacion : "IdPromocion"
  Cliente ||--o{ Contratacion : "IdCliente"
  Cliente |o--o{ Contratacion : "IdReferenteAcreditado"
  Usuario ||--o{ DictamenContable : "IdUsuario"
  Promocion ||--o{ DictamenContable : "IdPromocion"
  Promocion |o--o{ HistorialCobro : "IdPromocion"
  Cliente ||--o{ HistorialCobro : "IdCliente"
  Usuario |o--o{ Promocion : "IdUsuarioAlta"
  SugerenciaPromocion |o--o{ Promocion : "IdSugerenciaOrigen"
  PlanSuscripcion |o--o{ Promocion : "IdPlan"
  Promocion ||--o{ PromocionHistorial : "IdPromocion"
  Usuario |o--o{ PromocionHistorial : "IdUsuario"
  Promocion ||--o{ SolicitudBajaPromocion : "IdPromocion"
  Usuario ||--o{ SolicitudBajaPromocion : "IdUsuarioSolicita"
  Usuario |o--o{ SolicitudBajaPromocion : "IdUsuarioResuelve"
  Usuario |o--o{ SugerenciaPromocion : "IdUsuarioAlta"
  PlanSuscripcion |o--o{ SugerenciaPromocion : "IdPlan"
  Usuario
  PlanSuscripcion
  SugerenciaPromocion
  Promocion
  PromocionHistorial
  DictamenContable
  SolicitudBajaPromocion
  Contratacion
  Cliente
  HistorialCobro
