erDiagram
  Cliente ||--o{ CargoPrenda : "IdCliente"
  Cliente |o--o{ Cliente : "IdClienteReferente"
  MedioPago |o--o{ Cliente : "IdMedioPagoPreferido"
  PlanSuscripcion |o--o{ Cliente : "IdPlanSiguiente"
  PlanSuscripcion |o--o{ Cliente : "IdPlan"
  Promocion |o--o{ Contratacion : "IdPromocion"
  Empleado ||--o{ Contratacion : "IdVendedor"
  Empleado |o--o{ Contratacion : "IdCaja"
  PlanSuscripcion ||--o{ Contratacion : "IdPlan"
  MedioPago |o--o{ Contratacion : "IdMedioPago"
  PlanCuotas |o--o{ Contratacion : "IdPlanCuotas"
  Cliente ||--o{ Contratacion : "IdCliente"
  Cliente |o--o{ Contratacion : "IdReferenteAcreditado"
  Empleado |o--o{ ContratacionIntentoPago : "IdCaja"
  MedioPago |o--o{ ContratacionIntentoPago : "IdMedioPago"
  Contratacion ||--o{ ContratacionIntentoPago : "IdContratacion"
  PlanSuscripcion |o--o{ DesistimientoContratacion : "IdPlan"
  Cliente ||--o{ DesistimientoContratacion : "IdCliente"
  Empleado ||--o{ DesistimientoContratacion : "IdVendedor"
  PlanSuscripcion |o--o{ Promocion : "IdPlan"
  Cliente
  PlanSuscripcion
  Empleado
  Contratacion
  MedioPago
  PlanCuotas
  ContratacionIntentoPago
  DesistimientoContratacion
  Promocion
  CargoPrenda
